parser: '@typescript-eslint/parser'

env:
  browser: true
  es2017: true
  node: true
  mocha: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - plugin:react/recommended
  - plugin:prettier/recommended

parserOptions:
  ecmaVersion: 2017
  sourceType: module
  ecmaFeatures:
    jsx: true

rules:
  eqeqeq: [error, allow-null]
  prefer-const: error
  no-undef: off
  no-unused-vars: off
  '@typescript-eslint/ban-ts-ignore': off
  '@typescript-eslint/no-use-before-define': off
  '@typescript-eslint/no-explicit-any': off

plugins:
  - react

settings:
  react:
    version: detect

overrides:
  - files: ['webpack.config.js']
    rules:
      '@typescript-eslint/no-var-requires': off
